sudo: required
services: docker
language: elixir

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - ninja-build
cache:
  directories:
    - $HOME/cmake
env:
  global:
    - PATH=$HOME/cmake/bin:$PATH
matrix:
  include:
    - otp_release: 17.0
      env: CXX=g++-6 CC=gcc-6
    - otp_release: 17.5
      env: CXX=g++-6 CC=gcc-6
    - otp_release: 18.0
      env: CXX=g++-6 CC=gcc-6
    - otp_release: 18.3
      env: CXX=g++-6 CC=gcc-6
    - otp_release: 19.0
      env: CXX=g++-4.9 CC=gcc-4.9
    - otp_release: 19.0
      env: CXX=g++-5 CC=gcc-5
    - otp_release: 19.0
      env: CXX=g++-6 CC=gcc-6
    - otp_release: 19.0
      env: CXX=clang++-3.6 CC=clang-3.6
    - otp_release: 19.0
      env: CXX=clang++-3.7 CC=clang-3.7
    - otp_release: 19.0
      env: CXX=clang++-3.8 CC=clang-3.8

elixir:
  - 1.3

before_install:
  - docker run --name neo4j -d -p 7687:7687 -e 'NEO4J_AUTH=none' neo4j:3.0.6
  - docker logs -f neo4j | sed /Bolt\ enabled/q

script:
  - mix test
